# To jest Blueprint - opis całej Twojej aplikacji dla Render.com

services:
  # 1. Usługa Bazy Danych
  - type: psql         # Używamy PostgreSQL
    name: crownclinic-db
    plan: free         # Plan darmowy
    # Render automatycznie zarządza tą usługą

  # 2. Usługa Backendu
  - type: web
    name: crownclinic-backend
    env: docker
    dockerfilePath: ./Dockerfile # Używa Dockerfile z tego repozytorium
    plan: free
    healthCheckPath: /actuator/health # Sprawdza, czy aplikacja żyje
    envVars:
      # Zmienne do połączenia z bazą danych (Render dostarczy je automatycznie)
      - key: DB_HOST
        fromDatabase:
          name: crownclinic-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: crownclinic-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: crownclinic-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: crownclinic-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: crownclinic-db
          property: password
      # Zmienna z adresem frontendu, potrzebna do przekierowania OAuth2
      - key: FRONTEND_URL
        value: https://crownclinic-frontend.onrender.com # Ważne: to musi być publiczny URL frontendu
      # Twoje sekrety - ustawisz je ręcznie w panelu Render
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false

  # 3. Usługa Frontendu
  - type: web
    name: crownclinic-frontend
    env: docker
    repo: https://github.com/Widlakolak/crownclinic-frontend.git # <-- Wskazujemy na repo frontendu!
    dockerfilePath: ./Dockerfile # Używa Dockerfile z repozytorium frontendu
    plan: free
    envVars:
      # Kluczowa zmienna - mówi frontendowi, gdzie jest backend
      - key: BACKEND_URL
        # Render tworzy wewnętrzną sieć. Używamy nazwy usługi i portu.
        value: http://crownclinic-backend:8080
      # Ustawiamy port dla aplikacji Vaadin
      - key: PORT
        value: 8081
